export type Role = 'superadmin' | 'admin' | 'staff' | 'ortu'
export type Division = 'all' | 'banin' | 'banat'
export type Gender = 'male' | 'female'
export type SantriStatus = 'active' | 'alumni' | 'keluar'
export type OrgStatus = 'active' | 'suspended' | 'trial'
export type TopupRequestStatus = 'pending' | 'approved' | 'rejected'
export type TipeTransaksi =
  | 'deposit_cash'
  | 'deposit_transfer'
  | 'withdrawal'
  | 'pos_deduct'
  | 'adjustment'
export type PosStatus = 'success' | 'void'
export type StokLogType = 'masuk' | 'keluar' | 'koreksi'
export type CoaType = 'revenue' | 'cogs' | 'expense' | 'asset' | 'liability' | 'equity'
export type JurnalRefType = 'pos_transaksi' | 'topup' | 'withdrawal' | 'manual'
export type WithdrawalInterval = 'daily' | 'weekly' | 'monthly'
